on:
  push:
    branches:
      - main
env:
  aws_s3_response: {}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      # sam build 
      # - name: Build app
      #   run: sam build --use-container
      - name: Package app
        id: package-app
        run: sam package --use-json --s3-bucket folautech-lambda-container --s3-prefix aws-lambda-with-github-action --region us-west-2 >> $aws_s3_response
      - name: List out project
        run: ls -la
      - name: Display package response
        run: echo ${{ aws_s3_response }}
